version: "3.6"

services:
  app:
    build:
      context: node
    restart: always
    container_name: app_node
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - intranet

  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    tty: true
    ports:
      - 3306:3306
    networks:
      - intranet

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - db
      - app
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://app:3000"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  intranet:
    driver: bridge
